const CREATE = 'CREATE';
const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST';
const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS';
const FETCH_ALL_FAIL = 'FETCH_ALL_FAIL';
const FETCH_ALL = 'FETCH_ALL';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const REGISTER = 'REGISTER';
const LOGOUT_USER = 'LOGOUT_USER';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export {
  FETCH_ALL_REQUEST,
  FETCH_ALL_SUCCESS,
  FETCH_ALL_FAIL,
  FETCH_ALL,
  CREATE,
  UPDATE,
  DELETE,
  REGISTER,
  LOGOUT_USER,
  SIGN_UP_ERROR,
};
