const CREATE = 'CREATE';
const FETCH_ALL = 'FETCH_ALL';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const REGISTER = 'REGISTER';
const LOGOUT_USER = 'LOGOUT_USER';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
const SEARCH = 'SEARCH';
const SHOW_FORM = 'SHOW_FORM';
const HIDE_FORM = 'HIDE_FORM';
const SIGN_IN = 'SIGN_IN';

export {
  FETCH_ALL,
  CREATE,
  UPDATE,
  DELETE,
  REGISTER,
  SIGN_IN,
  LOGOUT_USER,
  SIGN_UP_ERROR,
  FETCH_ALL_USERS,
  CLEAR_MESSAGE,
  SEARCH,
  SHOW_FORM,
  HIDE_FORM,
};
