export const SETUP_TRAINING_BEGIN = 'SETUP_TRAINING_BEGIN';
export const SETUP_TRAINING_SUCCESS = 'SETUP_TRAINING_SUCCESS';
export const SETUP_TRAINING_ERROR = 'SETUP_TRAINING_ERROR';

export const GET_TRAINING_BEGIN = 'GET_TRAINING_BEGIN';
export const GET_TRAINING_SUCCESS = 'GET_TRAINING_SUCCESS';
export const GET_TRAINING_ERROR = 'GET_TRAINING_ERROR';
