export const SETUP_TRAINING_BEGIN = 'SETUP_TRAINING_BEGIN';
export const SETUP_TRAINING_SUCCESS = 'SETUP_TRAINING_SUCCESS';
export const SETUP_TRAINING_ERROR = 'SETUP_TRAINING_ERROR';

export const GET_TRAINING_BEGIN = 'GET_TRAINING_BEGIN';
export const GET_TRAINING_SUCCESS = 'GET_TRAINING_SUCCESS';
export const GET_TRAINING_ERROR = 'GET_TRAINING_ERROR';

export const SETUP_GET_TRAININGS_BEGIN = 'SETUP_GET_TRAININGS_BEGIN';
export const SETUP_GET_TRAININGS_SUCCESS = 'SETUP_GET_TRAININGS_SUCCESS';
export const SETUP_GET_TRAININGS_ERROR = 'SETUP_GET_TRAININGS_ERROR';

export const POST_TRAINING_BEGIN = 'POST_TRAINING_BEGIN';
export const POST_TRAINING_SUCCESS = 'POST_TRAINING_SUCCESS';
export const POST_TRAINING_ERROR = 'POST_TRAINING_ERROR';

export const DELETE_TRAINING_BEGIN = 'DELETE_TRAINING_BEGIN';
export const DELETE_TRAINING_SUCCESS = 'DELETE_TRAINING_SUCCESS';
export const DELETE_TRAINING_ERROR = 'DELETE_TRAINING_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
